### ISSUE TITLE
Server Compatibility

### ISSUE THREAD

**Issue by mcbridet** [GrzybDev/BFBC2_Hook#1]
Hi, great project! 

I've had success getting this working on the latest BFBC2 client, but not server. Which server are you testing or using with this hook? I am currently trying Bc2emu_V09 from MASE.

Cheers.

**Comment by GrzybDev** [comment]
Hi, server from MASE should also work - just make sure that the ports are correct (you can check them in Win32Game.cfg)

In BFBC2_Hook the defaults are using latest(!) port configuration from EA - As far as I remember MASE is using old ports :)

**Comment by GrzybDev** [comment]
I suppose the old port configuration looked like this:

SERVER_PLASMA_PORT: 19021
SERVER_THEATER_PORT: 19026

So, try adding this to hook config:

```
"client":{
      "serverPlasmaPort": 19021,
      "serverTheaterPort": 19026
},
```

**Comment by GrzybDev** [comment]
Did you updated the ports as I instructed?

What's your Win32Game.cfg file.

**Comment by mcbridet** [comment]
> Did you updated the ports as I instructed?
> 
> What's your Win32Game.cfg file.

At the moment it is "-server -dedicated", I tried adding the ports to config.json but it didn't seem to do anything.

Do you know what the syntax is for the `win32game.cfg` file, can't seem to find a good online reference. :)

Cheers.

**Comment by GrzybDev** [comment]
I don't remember syntax for that file too, try to change ports that hook listens to old ones as I said previously:

> I suppose the old port configuration looked like this:
> 
> SERVER_PLASMA_PORT: 19021 SERVER_THEATER_PORT: 19026
> 
> So, try adding this to hook config:
> 
> ```
> "client":{
>       "serverPlasmaPort": 19021,
>       "serverTheaterPort": 19026
> },
> ```

**Comment by GrzybDev** [comment]
![image](https://user-images.githubusercontent.com/58396043/227390064-1c4a748c-89e2-4ba9-af2f-958a3be7d049.png)
I just downloaded MASE Bc2emu, after changing the ports in hook config it works fine for me

**Comment by mcbridet** [comment]
Cool, I'll keep digging, thanks for the port changes suggestion. Awesome project btw. :)

**Comment by GrzybDev** [comment]
Not sure why are you forcing clientType in config, probably that's the issue too
My config looked like this:
`
{
	"client":{
           "serverPlasmaPort": 19021,
           "serverTheaterPort": 19026
	}
}
`

And it worked flawlessly

**Comment by GrzybDev** [comment]
Btw. The current up-to-date `win32game.cfg` includes this: `-feslhost bfbc2-pc-server.fesl.ea.com:18321 -theaterhost bfbc2-pc-server.theater.ea.com:18326`

With that, server hook doesn't even need any config file to connect to my demo server ;)

**Comment by GrzybDev** [comment]
@mcbridet  I'd suggest to update win32game.cfg instead of overriding hook port, and actually temporarily remove hook config, by default it's verbose enough, and if any error happens it should print it :)
