### ISSUE TITLE
Hosting & consoles

### ISSUE THREAD

**Issue by madmaxgrey** [GrzybDev/BFBC2_Hook#2]
can this work for console players, if its being hosted specifcly for that, or is it PC only and only PC players can play and host

**Comment by GrzybDev** [comment]
Hi, this specific Hook is designed for Windows version of Battlefield: Bad Company 2, both this hook and Master Server is designed mainly for PC - because I have no way to test it on consoles and also console hacking very differs from PC modding/hacking.
